### ISSUE TITLE
Unknown file extension ".tmp"

### ISSUE THREAD

**Issue by aidenpearce79** [Miramac/vscode-exec-node#31]
```
Info: Start process (1:58:47 AM)
Error: 
(node:14708) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.

Error: 
....\node_0e887f6e63be8.tmp:1
  import * as parser from "@babel/parser";
  ^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

Info: End process (1:58:47 AM)
```
After i add "type: module"

```
Info: Start process (2:01:25 AM)
Error: 
(node:5940) ExperimentalWarning: The ESM module loader is experimental.

Error: 
internal/modules/run_main.js:54
    internalBinding('errors').triggerUncaughtException(
                              ^

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".tmp" for ..\node_1081103c41c90.tmp
    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:65:15)
    at Loader.getFormat (internal/modules/esm/loader.js:113:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:244:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Loader.import (internal/modules/esm/loader.js:178:17) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}

Info: End process (2:01:25 AM)
```

**Comment by Miramac** [comment]
I'm sorry, that's not possible right now.
With the current Node.js version you can only use the CommonJS module system:
````
const parser = require("@babel/parser");
````
